# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2023-12-12 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_auto_20231212_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='framesize',
            name='description',
            field=models.CharField(blank=True, help_text=b'Please enter description for this Frame Size', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='framesize',
            name='ett_toptube',
            field=models.IntegerField(blank=True, default=0, verbose_name=b'Frame ETT in mm'),
        ),
        migrations.AddField(
            model_name='framesize',
            name='headtube',
            field=models.IntegerField(blank=True, default=0, verbose_name=b'Frame HEADtube in mm'),
        ),
        migrations.AddField(
            model_name='framesize',
            name='headtube_angle',
            field=models.FloatField(blank=True, default=0, verbose_name=b'HEADtube angle (degree)'),
        ),
        migrations.AddField(
            model_name='framesize',
            name='letter',
            field=models.CharField(blank=True, help_text=b'Please enter LETTER of frame size', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='framesize',
            name='rider_height_max',
            field=models.PositiveSmallIntegerField(default=0, help_text=b'Rider MAX height (cm)'),
        ),
        migrations.AddField(
            model_name='framesize',
            name='rider_height_min',
            field=models.PositiveSmallIntegerField(default=0, help_text=b'Rider MIN height (cm)'),
        ),
        migrations.AddField(
            model_name='framesize',
            name='seattube',
            field=models.IntegerField(blank=True, default=0, verbose_name=b'Seattube size in mm'),
        ),
        migrations.AddField(
            model_name='framesize',
            name='seattube_angle',
            field=models.FloatField(blank=True, default=0, verbose_name=b'Seat tube angle in degree'),
        ),
        migrations.AddField(
            model_name='framesize',
            name='standover',
            field=models.IntegerField(blank=True, default=0, verbose_name=b'how many milimiters on frame standover'),
        ),
        migrations.AddField(
            model_name='framesize',
            name='wheelbase',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name=b'Wheelbase size in mm'),
        ),
    ]
