# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2023-12-19 14:39
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0018_auto_20231212_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('start_week_day', models.PositiveSmallIntegerField(default=1)),
                ('end_week_day', models.PositiveSmallIntegerField(default=7)),
                ('start_time', models.TimeField(default=datetime.time(10, 0))),
                ('end_time', models.TimeField(default=datetime.time(19, 0))),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_date', 'start_week_day'],
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=100)),
                ('phone1', models.CharField(blank=True, max_length=100, null=True)),
                ('phone2', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('web_site', models.URLField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('map_point', models.TextField(blank=True, null=True)),
                ('ip_addr', models.GenericIPAddressField(blank=True, null=True, protocol=b'IPv4')),
                ('status', models.BooleanField(default=True)),
                ('casa_server_ip', models.GenericIPAddressField(blank=True, null=True, protocol=b'IPv4')),
                ('casa_server_port', models.PositiveSmallIntegerField(default=8123, null=True)),
                ('casa_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('XLICENSEKEY', models.CharField(blank=True, max_length=255, null=True)),
                ('PIN_CODE', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(max_length=255)),
                ('user_list', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL)),
                ('work_schedule', models.ManyToManyField(blank=True, to='accounting.Schedules')),
            ],
            options={
                'ordering': ['name', 'address'],
            },
        ),
        migrations.AddField(
            model_name='cashtype',
            name='cash',
            field=models.BooleanField(default=False, verbose_name=b'\xd0\x93\xd0\xbe\xd1\x82\xd1\x96\xd0\xb2\xd0\xba\xd0\xb0'),
        ),
        migrations.AddField(
            model_name='cashtype',
            name='pay_status',
            field=models.BooleanField(default=False, verbose_name=b'\xd0\x9f\xd0\xbb\xd0\xb0\xd1\x82\xd1\x96\xd0\xb6\xd0\xbd\xd0\xb8\xd0\xb9 \xd1\x82\xd0\xb8\xd0\xbf. \xd0\x92\xd1\x80\xd0\xb0\xd1\x85\xd0\xbe\xd0\xb2\xd1\x83\xd1\x94\xd1\x82\xd1\x8c\xd1\x81\xd1\x8f \xd0\xb2 \xd0\xbe\xd0\xbf\xd0\xbb\xd0\xb0\xd1\x82\xd0\xb0\xd1\x85'),
        ),
        migrations.AddField(
            model_name='cashtype',
            name='term',
            field=models.BooleanField(default=False, verbose_name=b'\xd0\xa2\xd0\xb5\xd1\x80\xd0\xbc\xd1\x96\xd0\xbd\xd0\xb0\xd0\xbb\xd0\xb8 \xd0\xb0\xd0\xb1\xd0\xbe \xd0\xb1\xd1\x83\xd0\xb4\xd1\x8c-\xd1\x8f\xd0\xba\xd0\xb8\xd0\xb9 \xd0\xb5\xd0\xba\xd0\xb2\xd0\xb0\xd1\x94\xd1\x80\xd0\xb8\xd0\xbd\xd0\xb3. \xd0\x92\xd1\x80\xd0\xb0\xd1\x85\xd0\xbe\xd0\xb2\xd1\x83\xd1\x94\xd1\x82\xd1\x8c\xd1\x81\xd1\x8f \xd1\x83 \xd0\xba\xd0\xb0\xd1\x81\xd0\xbe\xd0\xb2\xd0\xbe\xd0\xbc\xd1\x83 \xd0\xbe\xd0\xb1\xd0\xbb\xd1\x96\xd0\xba\xd1\x83.'),
        ),
#        migrations.AddField(
#            model_name='catalog',
#            name='date',
#            field=models.DateField(blank=True, null=True),
#        ),
#        migrations.AddField(
#            model_name='catalog',
#            name='full_description',
#            field=models.TextField(blank=True, null=True),
#        ),
#        migrations.AddField(
#            model_name='catalog',
#            name='youtube_url',
#            field=models.ManyToManyField(blank=True, to='accounting.YouTube'),
#        ),
        migrations.AlterField(
            model_name='cashtype',
            name='name',
            field=models.CharField(max_length=100, verbose_name=b'\xd0\x9d\xd0\xb0\xd0\xb7\xd0\xb2\xd0\xb0 \xd0\xb4\xd0\xbb\xd1\x8f \xd1\x82\xd0\xb8\xd0\xbf\xd1\x83 \xd0\xbe\xd0\xbf\xd0\xbb\xd0\xb0\xd1\x82\xd0\xb8'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='date_end',
            field=models.DateField(default=datetime.date(2023, 12, 22)),
        ),
#        migrations.AlterUniqueTogether(
#            name='clientdebts',
#            unique_together=set([('client', 'date', 'price', 'cash', 'description')]),
#        ),
        migrations.AddField(
            model_name='cashtype',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.Shop'),
        ),
        migrations.AddField(
            model_name='shopdailysales',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Shop'),
        ),
    ]
