# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2023-12-21 11:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_auto_20231219_1439'),
    ]

    operations = [
        # migrations.AddField(
            # model_name='catalog',
            # name='date',
            # field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
            # model_name='catalog',
            # name='full_description',
            # field=models.TextField(blank=True, null=True),
        # ),
        # migrations.AddField(
            # model_name='catalog',
            # name='youtube_url',
            # field=models.ManyToManyField(blank=True, to='accounting.YouTube'),
        # ),
        migrations.AddField(
            model_name='clientcredits',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Shop'),
        ),
        migrations.AddField(
            model_name='clientdebts',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Shop'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='date_end',
            field=models.DateField(default=datetime.date(2023, 12, 24)),
        ),
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
#        migrations.AlterUniqueTogether(
#            name='clientdebts',
#            unique_together=set([('client', 'date', 'price', 'cash', 'description')]),
#        ),
    ]
