# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2023-12-21 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_auto_20231221_1157'),
    ]

    operations = [
        # migrations.AddField(
            # model_name='catalog',
            # name='date',
            # field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
            # model_name='catalog',
            # name='full_description',
            # field=models.TextField(blank=True, null=True),
        # ),
        # migrations.AddField(
            # model_name='catalog',
            # name='youtube_url',
            # field=models.ManyToManyField(blank=True, to='accounting.YouTube'),
        # ),
        migrations.AddField(
            model_name='clientinvoice',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Shop'),
        ),
        # migrations.AlterUniqueTogether(
            # name='clientdebts',
            # unique_together=set([]),
        # ),
    ]
