# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2023-12-22 18:54
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0021_auto_20231221_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='bicycle_order',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Shop', verbose_name=b'\xd0\x9c\xd0\xb0\xd0\xb3\xd0\xb0\xd0\xb7\xd0\xb8\xd0\xbd'),
        ),
        migrations.AddField(
            model_name='bicycle_sale',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Shop', verbose_name=b'\xd0\x9c\xd0\xb0\xd0\xb3\xd0\xb0\xd0\xb7\xd0\xb8\xd0\xbd'),
        ),
        migrations.AddField(
            model_name='bicycle_storage',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Shop', verbose_name=b'\xd0\x9c\xd0\xb0\xd0\xb3\xd0\xb0\xd0\xb7\xd0\xb8\xd0\xbd'),
        ),
        migrations.AddField(
            model_name='bicycle_store',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Shop', verbose_name=b'\xd0\x9c\xd0\xb0\xd0\xb3\xd0\xb0\xd0\xb7\xd0\xb8\xd0\xbd'),
        ),
        # migrations.AddField(
            # model_name='catalog',
            # name='date',
            # field=models.DateField(blank=True, null=True),
        # ),
        # migrations.AddField(
            # model_name='catalog',
            # name='full_description',
            # field=models.TextField(blank=True, null=True),
        # ),
        # migrations.AddField(
            # model_name='catalog',
            # name='youtube_url',
            # field=models.ManyToManyField(blank=True, to='accounting.YouTube'),
        # ),
        migrations.AddField(
            model_name='checkpay',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Shop'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Shop', verbose_name=b'\xd0\x9c\xd0\xb0\xd0\xb3\xd0\xb0\xd0\xb7\xd0\xb8\xd0\xbd'),
        ),
        migrations.AddField(
            model_name='clientreturn',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Shop', verbose_name=b'\xd0\x9c\xd0\xb0\xd0\xb3\xd0\xb0\xd0\xb7\xd0\xb8\xd0\xbd'),
        ),
        migrations.AddField(
            model_name='country',
            name='ukr_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dealer',
            name='brand_list',
            field=models.ManyToManyField(blank=True, to='accounting.Manufacturer'),
        ),
        migrations.AddField(
            model_name='inventorylist',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Shop', verbose_name=b'\xd0\x9c\xd0\xb0\xd0\xb3\xd0\xb0\xd0\xb7\xd0\xb8\xd0\xbd'),
        ),
        migrations.AddField(
            model_name='invoicecomponentlist',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Shop', verbose_name=b'\xd0\x9c\xd0\xb0\xd0\xb3\xd0\xb0\xd0\xb7\xd0\xb8\xd0\xbd'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='bikecompany',
            field=models.BooleanField(default=False, verbose_name=b'\xd0\x9a\xd0\xbe\xd0\xbc\xd0\xbf\xd0\xb0\xd0\xbd\xd1\x96\xd1\x8f \xd1\x8f\xd0\xba\xd0\xb0 \xd0\xb2\xd0\xb8\xd0\xb3\xd0\xbe\xd1\x82\xd0\xbe\xd0\xb2\xd0\xbb\xd1\x8f\xd1\x94 \xd0\xb2\xd0\xb5\xd0\xbb\xd0\xbe\xd1\x81\xd0\xb8\xd0\xbf\xd0\xb5\xd0\xb4\xd0\xb8?'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='component',
            field=models.BooleanField(default=False, verbose_name=b'\xd0\x9a\xd0\xbe\xd0\xbc\xd0\xbf\xd0\xb0\xd0\xbd\xd1\x96\xd1\x8f \xd1\x8f\xd0\xba\xd0\xb0 \xd0\xb2\xd0\xb8\xd0\xb3\xd0\xbe\xd1\x82\xd0\xbe\xd0\xb2\xd0\xbb\xd1\x8f\xd1\x94 \xd0\xba\xd0\xbe\xd0\xbc\xd0\xbf\xd0\xbe\xd0\xbd\xd0\xb5\xd0\xbd\xd1\x82\xd0\xb8?'),
        ),
        migrations.AddField(
            model_name='photo',
            name='check_del',
            field=models.BooleanField(default=False, verbose_name=b'\xd0\x9f\xd0\xb5\xd1\x80\xd0\xb5\xd0\xb2\xd1\x96\xd1\x80\xd0\xb8\xd1\x82\xd0\xb8 \xd0\xbf\xd0\xb5\xd1\x80\xd0\xb5\xd0\xb4 \xd0\xb2\xd0\xb8\xd0\xb4\xd0\xb0\xd0\xbb\xd0\xb5\xd0\xbd\xd0\xbd\xd1\x8f\xd0\xbc?'),
        ),
        migrations.AddField(
            model_name='rent',
            name='shop_giving',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_give', to='accounting.Shop', verbose_name=b'\xd0\x9c\xd0\xb0\xd0\xb3\xd0\xb0\xd0\xb7\xd0\xb8\xd0\xbd \xd0\xb2\xd0\xb8\xd0\xb4\xd0\xb0\xd0\xb2'),
        ),
        migrations.AddField(
            model_name='rent',
            name='shop_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_retun', to='accounting.Shop', verbose_name=b'\xd0\x9c\xd0\xb0\xd0\xb3\xd0\xb0\xd0\xb7\xd0\xb8\xd0\xbd \xd0\xbf\xd1\x80\xd0\xb8\xd0\xb9\xd0\xbd\xd1\x8f\xd0\xb2'),
        ),
        migrations.AddField(
            model_name='rent',
            name='user_return',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ureturn', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workday',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Shop', verbose_name=b'\xd0\x9c\xd0\xb0\xd0\xb3\xd0\xb0\xd0\xb7\xd0\xb8\xd0\xbd'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Shop', verbose_name=b'\xd0\x9c\xd0\xb0\xd0\xb3\xd0\xb0\xd0\xb7\xd0\xb8\xd0\xbd'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.WorkTicket', verbose_name=b'\xd0\x97\xd0\xb0\xd1\x8f\xd0\xb2\xd0\xba\xd0\xb0 \xd0\xb4\xd0\xbe \xd1\x8f\xd0\xba\xd0\xbe\xd1\x97 \xd0\xb2\xd1\x96\xd0\xb4\xd0\xbd\xd0\xbe\xd1\x81\xd0\xb8\xd1\x82\xd1\x8c\xd1\x81\xd1\x8f \xd1\x80\xd0\xbe\xd0\xb1\xd0\xbe\xd1\x82\xd0\xb0'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='time',
            field=models.PositiveIntegerField(default=0, verbose_name=b'\xd0\x92\xd0\xb8\xd1\x82\xd1\x80\xd0\xb0\xd1\x87\xd0\xb5\xd0\xbd\xd0\xbe \xd1\x87\xd0\xb0\xd1\x81\xd1\x83. (\xd0\xa5\xd0\xb2\xd0\xb8\xd0\xbb\xd0\xb8\xd0\xbd\xd0\xb8)'),
        ),
        migrations.AddField(
            model_name='workticket',
            name='bicycle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workticket',
            name='bike_part_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Type'),
        ),
        migrations.AddField(
            model_name='workticket',
            name='estimate_time',
            field=models.PositiveIntegerField(default=0, verbose_name=b'\xd0\x9f\xd1\x80\xd0\xbe\xd0\xb3\xd0\xbd\xd0\xbe\xd0\xb7\xd0\xbe\xd0\xb2\xd0\xb0\xd0\xbd\xd0\xb8\xd0\xb9 \xd1\x87\xd0\xb0\xd1\x81 \xd0\xb2 \xd0\x93\xd0\x9e\xd0\x94\xd0\x98\xd0\x9d\xd0\x90\xd0\xa5'),
        ),
        migrations.AddField(
            model_name='workticket',
            name='history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workticket',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Shop'),
        ),
        migrations.AlterField(
            model_name='bicycle_order',
            name='prepay',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bicycle_order',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='bicycle_order',
            name='sale',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='forumname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='date_end',
            field=models.DateField(default=datetime.date(2023, 12, 25)),
        ),
#        migrations.AlterUniqueTogether(
#            name='clientdebts',
#            unique_together=set([]),
#        ),
    ]
