# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2024-01-25 02:11
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0025_auto_20240124_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoxName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('mark_delete', models.BooleanField(default=False, verbose_name=b'\xd0\x9c\xd1\x96\xd1\x82\xd0\xba\xd0\xb0 \xd0\xbd\xd0\xb0 \xd0\xb2\xd0\xb8\xd0\xb4\xd0\xb0\xd0\xbb\xd0\xb5\xd0\xbd\xd0\xbd\xd1\x8f')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Shop', verbose_name=b'\xd0\x9c\xd0\xb0\xd0\xb3\xd0\xb0\xd0\xb7\xd0\xb8\xd0\xbd')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['shop', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StorageBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, default=0, null=True)),
                ('count_real', models.IntegerField(blank=True, default=0, null=True)),
                ('count_last', models.IntegerField(blank=True, default=0, null=True)),
                ('date_create', models.DateTimeField()),
                ('date_update', models.DateTimeField()),
                ('mark_del', models.BooleanField(default=False, verbose_name=b'\xd0\x9c\xd1\x96\xd1\x82\xd0\xba\xd0\xb0 \xd0\xbd\xd0\xb0 \xd0\xb2\xd0\xb8\xd0\xb4\xd0\xb0\xd0\xbb\xd0\xb5\xd0\xbd\xd0\xbd\xd1\x8f')),
                ('history', models.TextField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('box_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.BoxName')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Catalog')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Shop')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_create', to=settings.AUTH_USER_MODEL)),
                ('user_update', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_update', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_create', 'box_name', 'catalog'],
            },
        ),
        migrations.AlterField(
            model_name='rent',
            name='date_end',
            field=models.DateField(default=datetime.date(2024, 1, 28)),
        ),
        migrations.AddField(
            model_name='inventorylist',
            name='box_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.BoxName', verbose_name=b'\xd0\x9c\xd1\x96\xd1\x81\xd1\x86\xd0\xb5 \xd0\xb7\xd0\xbd\xd0\xb0\xd1\x85\xd0\xbe\xd0\xb4\xd0\xb6\xd0\xb5\xd0\xbd\xd0\xbd\xd1\x8f'),
        ),
    ]
