# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2024-02-03 01:52
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0026_auto_20240125_0211'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInvoiceStorageBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('date_create', models.DateTimeField(blank=True, null=True)),
                ('date_accept', models.DateTimeField(blank=True, null=True)),
                ('cinvoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.ClientInvoice')),
                ('sbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.StorageBox')),
                ('user_accept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='u_accept_cl', to=settings.AUTH_USER_MODEL)),
                ('user_create', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='u_create_cl', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_create', 'sbox'],
            },
        ),
        migrations.AlterModelOptions(
            name='boxname',
            options={'ordering': ['-pk', 'shop', 'name']},
        ),
        migrations.AlterField(
            model_name='rent',
            name='date_end',
            field=models.DateField(default=datetime.date(2024, 2, 6)),
        ),
    ]
